### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by clinzy25** [mlg87/pr-reviewer-slack-notify-action#53]
Full message

```
Run mlg87/pr-reviewer-slack-notify-action@v7.6.0
 [PR-REVIEWER-SLACK-NOTIFY-ACTION]  2022-12-06T01:26:21Z  info : START getSlackMessageId

/home/runner/work/_actions/mlg87/pr-reviewer-slack-notify-action/v7.6.0/webpack:/pr-reviewer-slack-notify/src/utils/fail.ts:32
    logger_1.logger.error(JSON.stringify(error));
^
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at fail (/home/runner/work/_actions/mlg87/pr-reviewer-slack-notify-action/v7.6.0/webpack:/pr-reviewer-slack-notify/src/utils/fail.ts:32:1)
    at /home/runner/work/_actions/mlg87/pr-reviewer-slack-notify-action/v7.6.0/webpack:/pr-reviewer-slack-notify/src/utils/getSlackMessageId.ts:84:1
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/mlg87/pr-reviewer-slack-notify-action/v7.6.0/webpack:/pr-reviewer-slack-notify/src/utils/getSlackMessageId.ts:29:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Has been working fine for a while

**Comment by mlg87** [comment]
Fixed: fail.ts no longer JSON.stringify()s the error object; it logs error.message only (src/utils/fail.ts).
